import type { Metadata } from "next";
import { Lato } from "next/font/google";
import FloatBtn from "../components/FloatBtn";
import Version from "@/components/Versions";
import Image from "next/image";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//className="flex items-center justify-center relative h-screen "
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-myColorWhite-500 dark:bg-myColorBlack-600 `}>
          {children}
          <FloatBtn />
          <Version />
      </body>
    </html>
  );
}
//bg-gradientLight dark:bg-gradientDark h-full
