import type { Metadata } from "next";
import { Lato } from "next/font/google";
import FloatBtn from "../components/FloatBtn";
import Version from "@/components/Versions";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} bg-gradientLight dark:bg-gradientDark h-full`}>
        <main className="flex items-center justify-center relative h-screen ">
          {children}
          <FloatBtn />
          <Version />
        </main>
      </body>
    </html>
  );
}
